// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `_ms_to_srt`, `_ms_to_vtt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`


            /// Export alignment results to SRT subtitle format.
///
/// Creates subtitle entries with one phrase per entry (merged words).
Future<String>  exportSrt({required AlignmentResult result , required int maxWordsPerLine }) => RustLib.instance.api.crateApiAlignmentExportSrt(result: result, maxWordsPerLine: maxWordsPerLine);

/// Export alignment results to WebVTT subtitle format.
Future<String>  exportWebvtt({required AlignmentResult result , required int maxWordsPerLine }) => RustLib.instance.api.crateApiAlignmentExportWebvtt(result: result, maxWordsPerLine: maxWordsPerLine);

            /// Result of a forced alignment operation.
class AlignmentResult  {
                /// The language used for alignment.
final String language;
/// Word-level timestamps.
final List<WordTimestamp> words;

                const AlignmentResult({required this.language ,required this.words ,});

                
                

                
        @override
        int get hashCode => language.hashCode^words.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is AlignmentResult &&
                runtimeType == other.runtimeType
                && language == other.language&& words == other.words;
        
            }

/// A single word (or character for CJK) with its time span.
class WordTimestamp  {
                /// The word or character text.
final String text;
/// Start time in milliseconds.
final double startMs;
/// End time in milliseconds.
final double endMs;

                const WordTimestamp({required this.text ,required this.startMs ,required this.endMs ,});

                
                

                
        @override
        int get hashCode => text.hashCode^startMs.hashCode^endMs.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is WordTimestamp &&
                runtimeType == other.runtimeType
                && text == other.text&& startMs == other.startMs&& endMs == other.endMs;
        
            }
            