// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'qwen_asr_bridge.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`


            /// Utility to apply streaming configuration to an engine.
Future<void>  applyStreamConfig({required QwenAsrEngine engine , required StreamConfig config }) => RustLib.instance.api.crateApiStreamingApplyStreamConfig(engine: engine, config: config);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QwenAsrStream>>
                abstract class QwenAsrStream implements RustOpaqueInterface {
                    /// Get the number of samples that have been processed.
/// 
/// Divide by 16000 to get duration in seconds.
 BigInt  audioCursorSamples();


/// Finalize the stream and emit remaining tokens.
/// 
/// Call this when the audio stream has ended. Returns any final
/// text delta that wasn't yet emitted.
 Future<String?>  finalize({required QwenAsrEngine engine });


/// Create a new streaming transcription session.
/// 
/// Pre-allocates buffer for 60 seconds of audio at 16kHz.
factory QwenAsrStream()=>RustLib.instance.api.crateApiStreamingQwenAsrStreamNew();


/// Get processed audio duration in seconds.
 double  processedSeconds();


/// Push audio samples and process incrementally.
/// 
/// [samples] must be f32 PCM at 16kHz, mono.
/// Returns newly emitted text delta, if any.
/// 
/// This method accumulates all audio internally - you can call it
/// repeatedly with new chunks as they arrive from the microphone.
 Future<String?>  pushAudio({required QwenAsrEngine engine , required List<double> samples });


/// Reset the stream for a new utterance.
/// 
/// Clears audio buffer and resets state, but preserves allocations.
 void  reset();


/// Get the full accumulated text so far.
/// 
/// This includes both stable text and any pending tokens.
 String  text();



                    
                }
                

/// Streaming configuration options.
class StreamConfig  {
                /// Audio chunk size in seconds (default: 2.0)
final double chunkSec;
/// Token rollback window (default: 5)
final int rollback;
/// Unfixed chunks before emitting (default: 2)
final int unfixedChunks;
/// Max new tokens per chunk (default: 32)
final int maxNewTokens;
/// Use past text conditioning (default: false)
final bool pastTextConditioning;

                const StreamConfig({required this.chunkSec ,required this.rollback ,required this.unfixedChunks ,required this.maxNewTokens ,required this.pastTextConditioning ,});

                static Future<StreamConfig>  default_()=>RustLib.instance.api.crateApiStreamingStreamConfigDefault();


                

                
        @override
        int get hashCode => chunkSec.hashCode^rollback.hashCode^unfixedChunks.hashCode^maxNewTokens.hashCode^pastTextConditioning.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is StreamConfig &&
                runtimeType == other.runtimeType
                && chunkSec == other.chunkSec&& rollback == other.rollback&& unfixedChunks == other.unfixedChunks&& maxNewTokens == other.maxNewTokens&& pastTextConditioning == other.pastTextConditioning;
        
            }
            